import type { NextPage } from 'next'
import { useEffect, useState } from "react";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import emojilib from "emojilib";

const Home: NextPage = () => {
  const [currentEmoji,setCurrentEmoji] = useState('');

  const selected = (key: string) => {
    setCurrentEmoji(key);
    console.log(currentEmoji);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>挑选今天的 Emoji 吧</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {currentEmoji 
      ? (<main onClick={() => setCurrentEmoji('')} className={styles.main}>
        <section className={styles.selected}>{currentEmoji}</section>
      </main>):
       (<main className={styles.main}>
        {Object.keys(emojilib).map((key) => {
          return (<span onClick={()=>selected(key)} key={key} className={styles.oneEmoji}>{key}</span>)
        })}
      </main>)}
    </div>
  )
}

export default Home
